for merge request
KeremDUZENLI/_REST-API-MYSQL-JWT_ pull request #1
Opened 2023-02-25 01:33 UTC by KeremDUZENLI

2023-02-27 12:27 UTC, RodolfoMRibeiro commented
Hey man, I recommend that u start following git commit patterns. Look at this article latter. 
That's the one I used to learn: https://medium.com/linkapi-solutions/conventional-commits-pattern-3778d1a1e657

2023-02-27 12:41 UTC, KeremDUZENLI commented
sure man

2023-02-28 15:35 UTC, RodolfoMRibeiro requested changes

2023-02-28 15:35 UTC, RodolfoMRibeiro commented on main.go
> +	routes.PersonRoutes(router)
encapsulate this functions inside a setup func. u might create a struct called server to work as a class and hold not only the routes, but also the run function that is responsible to run the server

2023-02-28 15:35 UTC, RodolfoMRibeiro commented on database/database.go
> +var MongoClient *mongo.Client = Database()
Avoid creating global variables, There is a huge change of their values be changed in somewhere into your code. So, its a nice practice to avoid creating them

2023-02-28 15:35 UTC, RodolfoMRibeiro commented on helper/tokenHelper.go
> +		log.Panic(err)
take care with panics or fatals, they might "destroy" your project execution. So, use them carefully

2023-02-28 15:35 UTC, RodolfoMRibeiro commented on helper/tokenHelper.go
> +var SECRET_KEY string = os.Getenv("SECRET_KEY")
if u are going to keep your environment variables into global variables (that what we do as well) keep them in another package. Kind of a `env` folder to hold it's value the environment variables and then import them to here

2023-02-28 15:35 UTC, RodolfoMRibeiro commented on controller/controller.go
> +		result.All(ctx, &allUsers)
put all this code lines into a service. I mean, any kind of data manipulation or business rules should be there in a onion archtecture

2023-03-01 18:27 UTC, merged